### ISSUE TITLE
Error: Cannot find module 'child-process-promise' on CI in vNext

### ISSUE THREAD

**Issue by larryonoff** [thaliproject/Thali_CordovaPlugin#1012]
https://raw.githubusercontent.com/ThaliTester/TestResults/81418577d35938f_CI_sanity_check__vNext__jareksl/build.md
```
Test runner loading file: /Users/thali/Github/Thali_CordovaPlugin/test/www/jxcore/meta_tests/testInstall.js
ERROR runTests: 
Uncaught Exception: Error: Error when loading file /Users/thali/Github/Thali_CordovaPlugin/test/www/jxcore/meta_tests/testInstall.js: Error: Cannot find module 'child-process-promise'
Error: Error when loading file /Users/thali/Github/Thali_CordovaPlugin/test/www/jxcore/meta_tests/testInstall.js: Error: Cannot find module 'child-process-promise'
    at loadFile (/Users/thali/Github/Thali_CordovaPlugin/test/www/jxcore/runTests.js:26:11)
    at module.exports.run (/Users/thali/Github/Thali_CordovaPlugin/test/www/jxcore/runTests.js:38:7)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/thali/Github/Thali_CordovaPlugin/test/www/jxcore/runTests.js:35:52)
    at Module._compile (module.js:619:26)
    at Object.Module._extensions..js (module.js:649:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:878:12)
    at startup (node.js:485:18)
    at node.js:1604:3
```

https://github.com/ThaliTester/TestResults/blob/8141857795f3cf9_CI_sanity_check__vNext__jareksl/build.md
```
module.js:802
    throw err;
          ^
Error: Cannot find module 'child-process-promise'
    at Function.Module._oldRes (module.js:800:15)
    at Function.Module._resolveFilename (module.js:1768:19)
    at Function.Module._load (module.js:360:25)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (/Users/thali/Github/ThaliTest/www/jxcore/node_modules/thali/install/install.js:3:12)
    at Module._compile (module.js:619:26)
    at Object.Module._extensions..js (module.js:649:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
```

**Comment by larryonoff** [comment]
Hope that the issue is fixed. At least CI is passing.
