### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by andrew-aladev** [thaliproject/Thali_CordovaPlugin#1138]
I've modified `thaliReplicationPeerAction` a bit.

```
ThaliReplicationPeerAction.prototype.start = function (httpAgentPool) {
  var self = this;

  var stackTrace = '';
  try {
    throw new Error("something");
  } catch (e) {
    stackTrace = e.stack;
  }
  ...

.on('error', function (err) {
  ...
  err.toString = function () {
    return util.format(
      'Got error on replication!, error: \'%s\', trace: \'%s\'',
      err.message, stackTrace
    );
  }
  self._complete([err]);
 ...
```

And I've found the problem in coordinated test `testThaliReplicationPeerActionCoordinated.js`.

```
2016-09-23 10:26:15 - DEBUG testUtils: 'Got an err - Got error on replication!, error: 'socket hang up -1', trace: 'Error: something
    at ThaliReplicationPeerAction.start (/root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/thali/NextGeneration/replication/thaliReplicationPeerAction.js:186:11)
    at /root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/test/www/jxcore/bv_tests/testThaliReplicationPeerActionCoordinated.js:138:40
```

When I was checking this bug I've found another one:

```
2016-09-23 09:59:53 - ERROR TestsProcess: 'uncaught promise rejection, error: 'Error: read ECONNRESET', stack: 'Error: read ECONNRESET
    at errnoException (net.js:837:11)
    at TCP.onread (net.js:519:19)
---------------------------------------------
    at CleartextStream.Readable.on (_stream_readable.js:657:33)
    at http.js:1383:12
    at process._tickCallback (node.js:924:13)
---------------------------------------------
    at ClientRequest.onSocket (http.js:1359:11)
    at ForeverAgentSSL.Agent.addRequest [as addRequestNoreuse] (http.js:895:9)
    at ForeverAgentSSL.ForeverAgent.addRequest (/root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/thali/node_modules/forever-agent/index.js:77:10)
    at new ClientRequest (http.js:1044:16)
    at Object.exports.request (https.js:100:10)
    at Request.start (/root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:753:32)
    at Request.end (/root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:1418:10)
    at end (/root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:580:14)
    at Object._onImmediate (/root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:594:7)
    at processImmediate [as _immediateCallback] (timers.js:370:15)''
```

All these problems are related to `testThaliPullReplicationFromNotificationCoordinated.js` and `testThaliReplicationPeerActionCoordinated.js`. These problems is related to `pouchdb.replication` and `action.start` and now we definitely know what we need to fix.

We should catch socket hang ups and connection refused like errors properly.

**Comment by larryonoff** [comment]
It's the highest priority now.

**Comment by andrew-aladev** [comment]
Socket hang up is fixed but we have another problem now.

```
2016-09-26 09:18:22 - DEBUG UnitTestFramework: '#run ok: 'Coordinated pull replication from notification test''
2016-09-26 09:18:22 - DEBUG UnitTestFramework: '#teardown: 'Coordinated pull replication from notification test''
...
# setup
...
# setup
...
2016-09-26 09:18:22 - ERROR TestsProcess: 'uncaught promise rejection, error: 'Error: connect ECONNREFUSED', stack: 'Error: connect ECONNREFUSED
    at errnoException (net.js:837:11)
    at Object.afterConnect [as oncomplete] (net.js:829:19)''
```

and

```
2016-09-26 09:10:20 - DEBUG UnitTestFramework: '#run ok: 'Coordinated replication action test''
2016-09-26 09:10:20 - DEBUG UnitTestFramework: '#teardown: 'Coordinated replication action test''
...
# setup
...
2016-09-26 09:10:20 - ERROR TestsProcess: 'uncaught promise rejection, error: 'Error: connect ECONNREFUSED', stack: 'Error: connect ECONNREFUSED
    at errnoException (net.js:837:11)
    at Object.afterConnect [as oncomplete] (net.js:829:19)''
```

**Comment by andrew-aladev** [comment]
I will finish this bug today.

**Comment by andrew-aladev** [comment]
This is not possible for us to fix this issue completely. I've inspected many big stack traces. We couldn't catch this exception. This exception is from `request.js` from `pouchdb`. I can show an example:

```
function stop (t) {
  return Promise.all(
    something.stop(),
    another.stop(),
    ...
  )
  .catch(function (error) {
    if (error.code in [ECONNREFUSED, ECONNRESET]) {
      logger.info('we don\'t care about error: \'%s\' while stopping', error);
      return;
    }
    return Promise.reject(error);
  });
}
```

I didn't find a simple way to catch exception from `request.js` in `pouchdb`. We need to create an issue for proper fix in future.

Now we have to create a reliable situation where we couldn't receive `ECONNREFUSED` and `ECONNRESET`. I've implemented `t.sync` and created a workaround:

```
function stop (t) {
  return Promise.all(
    something.stop(),
    ...
  )
  .then(function() {
    return t.sync();
  })
  .then(function () {
    return Promise.all(
      another.stop(),
      ...
    );
  });
}
```
