### ISSUE TITLE
PouchDB: We have an exception of PouchDB that we cannot catch, see the details

### ISSUE THREAD

**Issue by larryonoff** [thaliproject/Thali_CordovaPlugin#1184]
TBD: @andrew-aladev fill the description

**Comment by yaronyg** [comment]
Note that this came from thaliproject/Thali_CordovaPlugin#1138

**Comment by mohlsen** [comment]
Brief description:

The issue is that if PouchDB gets a connection failure then it throws a naked exception instead of cleanly issuing an error.

That naked exception is thrown deep in promise land so we have no way to really catch it and so it becomes an uncaught exception which makes Node extremely unhappy.

@larryonoff add more details if you can so we can go get this worked on in PouchDB.

**Comment by andrew-aladev** [comment]
Please checkout my branch `vNext_aaladev_1138`. Than open `test/www/jxcore/bv_tests/testThaliPullReplicationFromNotificationCoordinated.js`. 

```
.then(function () {
  // https://github.com/thaliproject/Thali_CordovaPlugin/issues/1138
  // workaround for ECONNREFUSED and ECONNRESET from 'request.js' in 'pouchdb'.
  return t.sync();
})
```

Please comment `return t.sync();` and run `test/www/jxcore && jx runCoordinatedTests.js --filter=bv_tests/testThaliPullReplicationFromNotificationCoordinated.js`. You will have 10% chance to receive uncaught exception/rejection, so you need to run this test at least 10 times.

**Comment by andrew-aladev** [comment]
This exception comes from `request.js`. I've read `request/request.js`. It looks almost impossible to fix this code. I think the best solution for `pouchdb` is to find alternative for `request.js`.

**Comment by larryonoff** [comment]
@yaronyg @mohlsen I've updated issue description, please see it. Please also see @andrew-aladev comments.

**Comment by andrew-aladev** [comment]
You can add `require('longjohn').async_trace_limit = -1;` into `test/www/jxcore/lib/utils/process.js` and run `cd test/www/jxcore && jx npm install longjohn`.

You will obtain 2 sorts of exceptions:
```
2016-09-28 09:11:10 - ERROR TestsProcess: 'uncaught promise rejection, error: 'Error: socket hang up -1', stack: 'Error: socket hang up -1
    at createHangUpError (http.js:1101:15)
    at CleartextStream.socketCloseListener (http.js:1150:23)
    at CleartextStream.emit (events.js:98:20)
    at tls.js:644:10
    at process._tickCallback (node.js:924:13)
---------------------------------------------
    at scheduleDrain (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:45:13)
    at immediate (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:71:5)
    at unwrap (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:85:3)
    at QueueItem.otherCallRejected (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:81:3)
    at Object.handlers.reject (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:136:19)
    at onError (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:159:14)
    at /root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:137:13
    at /root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:108:11
    at /root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/argsarray/index.js:14:18
    at /root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:2386:14
    at /root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5488:16
    at Request._callback (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5105:14)
    at self.callback (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at Request.emit (events.js:82:17)
    at Request.onRequestError (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:831:8)
    at ClientRequest.emit (events.js:82:17)
    at CleartextStream.socketCloseListener (http.js:1150:9)
    at CleartextStream.emit (events.js:98:20)
    at tls.js:644:10
    at process._tickCallback (node.js:924:13)
---------------------------------------------
    at Request.init (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:202:10)
    at new Request (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:142:8)
    at request (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/index.js:55:10)
    at ajaxCore (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5102:10)
    at PouchAlt.ajax [as _ajax] (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5135:10)
    at ajax$$ (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5284:16)
    at /root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5482:7
    at Array.0 (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:88:21)
    at nextTick (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:61:18)
    at process._tickCallback (node.js:924:13)
---------------------------------------------
    at scheduleDrain (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:45:13)
    at immediate (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:71:5)
    at unwrap (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:85:3)
    at QueueItem.otherCallFulfilled (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:75:3)
    at Object.handlers.resolve (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:115:21)
    at onSuccess (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:167:14)
    at Object.opts.complete (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:1460:9)
    at fetched (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:6047:14)
    at onSuccess (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5082:5)
    at Request._callback (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5124:7)
    at Request.self.callback (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at Request.emit (events.js:85:17)
    at Request.<anonymous> (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:1067:10)
    at Request.emit (events.js:98:20)
    at IncomingMessage.<anonymous> (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:988:12)
    at IncomingMessage.emit (events.js:98:20)
    at _stream_readable.js:889:16
    at process._tickCallback (node.js:924:13)
---------------------------------------------
    at Request.init (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:203:10)
    at new Request (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:142:8)
    at request (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/index.js:55:10)
    at ajaxCore (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5102:10)
    at PouchAlt.ajax [as _ajax] (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5135:10)
    at ajax$$ (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5284:16)
    at /root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5989:15
    at Array.0 (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:88:21)
    at nextTick (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:61:18)
    at process._tickCallback (node.js:924:13)
---------------------------------------------
    at scheduleDrain (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:45:13)
    at immediate (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/immediate/lib/index.js:71:5)
    at unwrap (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:85:3)
    at QueueItem.otherCallFulfilled (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:75:3)
    at Object.handlers.resolve (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:115:21)
    at onSuccess (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/lie/lib/index.js:167:14)
    at Object.opts.complete (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:1460:9)
    at fetched (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:6047:14)
    at onSuccess (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5082:5)
    at Request._callback (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/lib/index.js:5124:7)
    at Request.self.callback (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at Request.emit (events.js:85:17)
    at Request.<anonymous> (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:1067:10)
    at Request.emit (events.js:98:20)
    at IncomingMessage.<anonymous> (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:988:12)
    at IncomingMessage.emit (events.js:98:20)
    at _stream_readable.js:889:16
    at process._tickCallback (node.js:924:13)''
```

```
2016-09-28 09:14:00 - ERROR TestsProcess: 'uncaught promise rejection, error: 'Error: connect ECONNREFUSED', stack: 'Error: connect ECONNREFUSED
    at errnoException (net.js:837:11)
    at Object.afterConnect [as oncomplete] (net.js:829:19)
---------------------------------------------
    at CleartextStream.Readable.on (_stream_readable.js:657:33)
    at http.js:1383:12
    at process._tickCallback (node.js:924:13)
---------------------------------------------
    at ClientRequest.onSocket (http.js:1359:11)
    at ForeverAgentSSL.Agent.addRequest [as addRequestNoreuse] (http.js:895:9)
    at new ClientRequest (http.js:1044:16)
    at Object.exports.request (https.js:100:10)
    at Request.start (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:753:32)
    at Request.onRequestError (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:823:10)
    at ClientRequest.emit (events.js:82:17)
    at CleartextStream.socketCloseListener (http.js:1150:9)
    at CleartextStream.emit (events.js:98:20)
    at tls.js:644:10
    at process._tickCallback (node.js:924:13)
---------------------------------------------
    at Request.start (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:799:12)
    at Request.end (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:1418:10)
    at end (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:580:14)
    at Object._onImmediate (/root/workspace/vNext_aaladev_1138/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:594:7)
    at processImmediate [as _immediateCallback] (timers.js:370:15)''
```
