### ISSUE TITLE
What is causing the 500 socket hang up errors on native with test app?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1415]
In the native logs in #1356 which are:

> S7 logs: https://gist.github.com/czyzm/5a1a916c25dfe9156005ce87e0cce1c8
> Nexus logs: https://gist.github.com/czyzm/25b92d6ed662d5cb838e64eaedfdc2f9

We see a bunch of errors of the form:

10-24 15:07:21.567      8855    8909    I   jxcore-log   2016-10-24 13:07:21 - DEBUG thaliReplicationPeerAction: 'Got error on replication -  500 socket hang up'
10-24 15:07:21.567      8855    8909    I   jxcore-log   

The 500 socket hang up on replication error means that the replication code opened up a remote connection to the other phone, the request was sent and the connection was closed without ever receiving a response from the other side. Unfortunately PouchDB treats this as a 500 series error and so the entire replication fails. Which isn't that big a deal because we will automatically retry when we get a beacon. Which the logs show we do and keep failing with the same 500 series error.

I haven't seen this particular error pattern on Wifi or the Wifi based native mock. So this argues pretty strongly that the problem has to do with the interaction of the Android native layer and Node. But that doesn't actually mean that's true. What we need to do is to trace the failure that made us go out.

In other words we have to show that:
1. Phone A receives a BLE announcement of Phone B
2. Phone A receives a peerAvailabilityChanged event in thaliMobileNativeWrapper.js and since the peer is available that code will call createPeerListener which will then call connectToRemotePeer which will call the native Connect call. We need to see all of this in the logs.
3. On the Android side we need to see that the connect call happened, we need to see that the TCP/IP listener is created.
4. Once we get the connect callback we will then call handleForwardConnection which will call multiplextoNativeListener which sets up everything on the Node end.
5. At this point we are back in Android and we need to see that Android got an incoming TCP/IP connection. We need to see when data is received on the input stream and sent on the output stream. If the stream is terminated for any reason we need to know why! Did node close the TCP/IP connection? Did Android terminate the TCP/IP connection? In the node code I have instrumented every single place we call .end or .destroy so we can always see who initiated the closure. And we need this information for both incoming and outgoing connections via Android. When we get a Bluetooth server socket we relay that to a native TCP client. We need to show when that client is created. We need to show that it created a socket successfully with node. We need to show that data is flowing across that socket. If the socket is torn down we need to prove who did it. Did node terminate the socket on the server end? Did Android terminate the client socket because of a Bluetooth failure? What happened?

Basically what we need to know is - why are we getting the failed connection on replication? And why does this failure only happen on replication and not on beacon retrieval?

**Comment by yaronyg** [comment]
For testing purposes we should focus on https://github.com/czyzm/ThaliTestApp since it is closest to behaving like an actual customer application. Please configure that test app to run in native mode and set it up to use my master_add_logging branch which will give much more insight into what Node is doing. Match that by updating our Java code to make it very clear what is going on at the TCP layer.

**Comment by evabishchevich** [comment]
https://gist.github.com/evabishchevich/1a9172ae55ac051ee75b3be344bbdf58
https://gist.github.com/evabishchevich/62709b71e912ae723e34f786e33aacfb

**Comment by evabishchevich** [comment]
Thali 2
https://gist.github.com/evabishchevich/e79ba2469c1e61f92c368d3441ad1d5c
Thali 1
https://gist.github.com/evabishchevich/361ad2a34d15ea72e64edd708c228e56

**Comment by evabishchevich** [comment]
Thali2
https://gist.github.com/evabishchevich/aef05f2478581deea2be9e7cd6f5b96e
Thali 1
https://gist.github.com/evabishchevich/fe60b3cc04c6c04d5d7af5253e135cb2

**Comment by evabishchevich** [comment]
thali 1
https://gist.github.com/evabishchevich/dbef6cbfecb3c8a7f89f50f7599fe1b5
thali 2
https://gist.github.com/evabishchevich/1b6ed78479e79e0e31b6c956642dc797

**Comment by evabishchevich** [comment]
thali 1
https://gist.github.com/evabishchevich/3fa6ba61729d66169f63424741a0f1af
thali 2
https://gist.github.com/evabishchevich/261654ef3bb55af0fa9dc4ceaabe72ab

**Comment by evabishchevich** [comment]
thali 1
https://gist.github.com/evabishchevich/2fe306a172cf12dfc2e699d5b033aa4e
thali 2
https://gist.github.com/evabishchevich/af0fd480fc6e23982816f79dc648be4f

**Comment by evabishchevich** [comment]
Fresh app. Didn't press add data button
thali 1
https://gist.github.com/evabishchevich/9f1e0e0a5e826d0f94e13688b3d2bdca
thali 2
https://gist.github.com/evabishchevich/5b610337fd06fc4eccda9bfcf2ddba4a

**Comment by evabishchevich** [comment]
Thali 1
https://gist.github.com/evabishchevich/ab3d016e9ac39110be962799da2781c1
Thali 2
https://gist.github.com/evabishchevich/8d297e6ca993b419d102ac40547f7c1c

**Comment by andrew-aladev** [comment]
Today we were talking with @chapko and found a great result. We have 2 peers. One peer received error `had error Error: Channel destroyed`. Why? We've found this place.

Peer will say `Channel destroyed` when it received packet `0x04 0x00 0x06 0x00`. `4` is just a packet length and `6` is the error code. The meaning of this packet is `remote error`. Another peer sent this packet.

Another peer's `multiplex` will send `6` error only if this peer is a `initiator` of [`destroy`](https://github.com/maxogden/multiplex/blob/master/index.js#L70). So `Channel destroyed` means `another peer destroyed our channel`.

So we should look into another peer's log. In this log we have `incoming (TCP) - Node TCP/IP client <-> Mux stream- ... - 0 - error: Error: This socket is closed.`. This is a reason. We will continue investigating this error.

**Comment by andrew-aladev** [comment]
We have a typical log [here](https://gist.githubusercontent.com/andrew-aladev/0177a15d0f0a3cdac228904c6322be79/raw/5bcccdb6a9879c71d552b55a6c85074ab209878a/log.txt).

Peer `40baf507-afa8-42b6-b9bd-be0adb7787af` become available and than not available. Than it appears with new id `12a3cece-daba-48d4-b7e6-33f483410c1b`. Our log `This socket is closed` is related to the old socket.

**Comment by andrew-aladev** [comment]
I've tracked this packet. I've received the following results:

```
tcp onread, chunk: '^A]^V^C^C^@O^B^@^@K^C^CPk^�5��<U+B6625>#�&��\^\�ǹV�^NF2^R^U�dhi^@^@�^@^@#^@^@^@^@�^A^@^A^@^@#^@^@3t^@^R^Hhttp/1.http/1.0^V^C^C^@^D^N^@^@^@', stack: 'Error
    at TCP.onread (net.js:454:11)'
2016-11-02 12:24:40 - DEBUG createPeerListener: 'incoming (TCP) - Node TCP/IP client <-> Mux stream- urn:uuid:e5629472-127a-47de-bc3a-86fd189e4f81 - 0 - error: Error: This socket is closed, data: '^V^C^C^@O^B^@
^@K^C^CPk^�5��<U+B6625>#�&��\^\�ǹV�^NF2^R^U�dhi^@^@�^@^@#^@^@^@^@�^A^@^A^@^@#^@^@3t^@^R^Hhttp/1.http/1.0^V^C^C^@^D^N^@^@^@''
```

```
ololo, chunk: '^A]^V^C^C^@O^B^@^@K^C^Cu �^Y3q�^B#Z1Z<B�G�rm���M�]ESCz��f^XL^@^@�^@^@#^@^@^@^@�^A^@^A^@^@#^@^@3t^@^R^Hhttp/1.http/1.0^V^C^C^@^D^N^@^@^@', stack: 'Error
    at write (_stream_readable.js:559:13)
    at flow (_stream_readable.js:570:7)
    at Socket.pipeOnReadable (_stream_readable.js:600:5)
    at Socket.emit (events.js:79:17)
    at emitReadable_ (_stream_readable.js:390:10)
    at emitReadable (_stream_readable.js:386:5)
    at readableAddChunk (_stream_readable.js:144:31)
    at Socket.Readable.push (_stream_readable.js:108:10)
    at TCP.onread (net.js:487:18)
```

So we received some packet and tried to write it into socket, but socket has been already closed.

**Comment by andrew-aladev** [comment]
I've marked sockets with autoincrement ids. Socket that throws `This socket is closed` has `id: 3` for example. This socket was created (from `lib/net.js`) by

```
Server.prototype._listen2 = function(address, port, addressType, backlog, fd) {
  ...
  self._handle.onconnection = onconnection;
  ...
}

function onconnection(clientHandle) {
 ...
  var socket = new Socket({
    handle: clientHandle,
    allowHalfOpen: self.allowHalfOpen
  });
  ...
  self.emit('connection', socket);
}
```

So I am sure that this socket is `incoming`.

**Comment by andrew-aladev** [comment]
Who destroyed our incoming? It is `makeIntoCloseAllServer`. So the typical log is:

```
2016-11-02 13:54:30 - DEBUG thaliWifiInfrastructure: 'Emiting wifiPeerAvailabilityChanged {"peerIdentifier":"urn:uuid:35e4c552-9814-4bff-8bef-eb720221ab89","portNumber":null,"hostAddress":null}'
2016-11-02 13:54:30 - DEBUG thaliMobileNativeWrapper: 'Received peerAvailabilityChanged event from native layer [{"peerIdentifier":"urn:uuid:35e4c552-9814-4bff-8bef-eb720221ab89","peerAvailable":false,"pleaseCon
nect":false}]'
2016-11-02 13:54:30 - DEBUG thaliMobileNativeWrapper: 'Received peer availability changed event with {"peerIdentifier":"urn:uuid:35e4c552-9814-4bff-8bef-eb720221ab89","peerAvailable":false,"pleaseConnect":false}
'
2016-11-02 13:54:30 - DEBUG thaliMobileNativeWrapper: 'handlePeerUnavailable - Emitting {"peerIdentifier":"urn:uuid:35e4c552-9814-4bff-8bef-eb720221ab89","portNumber":null}'
2016-11-02 13:54:30 - DEBUG thaliMobile: 'Emitting peerAvailabilityChanged from handlePeer {"peerIdentifier":"urn:uuid:35e4c552-9814-4bff-8bef-eb720221ab89","hostAddress":null,"portNumber":null,"connectionType":
"AndroidBluetooth","suggestedTCPTimeout":5000}'
2016-11-02 13:54:30 - DEBUG thaliPeerPoolOneAtATime: 'action returned successfully from start - Action ID: 1, Action Type: GetRequestBeacon, Connection Type: AndroidBluetooth, Peer Identifier: urn:uuid:35e4c552-
9814-4bff-8bef-eb720221ab89'
2016-11-02 13:54:30 - DEBUG thaliTcpServersManager: 'Terminate outgoing connection called on peerID urn:uuid:35e4c552-9814-4bff-8bef-eb720221ab89 with port 62320'
2016-11-02 13:54:30 - DEBUG makeIntoCloseAllServer: 'closeAll called on server'
2016-11-02 13:54:30 - DEBUG createPeerListener: 'ololo incoming destroyed, stack: 'Error
    at Socket.incoming._destroy (/Users/hiqouser/workspace/aaladev_1407/Thali_CordovaPlugin/thali/NextGeneration/mux/createPeerListener.js:511:17)
    at Socket.destroy (net.js:448:8)
    at /Users/hiqouser/workspace/aaladev_1407/Thali_CordovaPlugin/thali/NextGeneration/makeIntoCloseAllServer.js:69:18
    at Array.forEach (native)
    at Server.server.closeAll (/Users/hiqouser/workspace/aaladev_1407/Thali_CordovaPlugin/thali/NextGeneration/makeIntoCloseAllServer.js:68:17)
    at Object.closeServer (/Users/hiqouser/workspace/aaladev_1407/Thali_CordovaPlugin/thali/NextGeneration/mux/createPeerListener.js:25:10)
    at ThaliTcpServersManager.terminateOutgoingConnection (/Users/hiqouser/workspace/aaladev_1407/Thali_CordovaPlugin/thali/NextGeneration/mux/thaliTcpServersManager.js:293:26)
    at /Users/hiqouser/workspace/aaladev_1407/Thali_CordovaPlugin/thali/NextGeneration/thaliPeerPool/thaliPeerPoolOneAtATime.js:198:12
    at Array.0 (/Users/hiqouser/workspace/aaladev_1407/Thali_CordovaPlugin/thali/node_modules/lie/lib/index.js:88:21)
    at nextTick (/Users/hiqouser/workspace/aaladev_1407/Thali_CordovaPlugin/thali/node_modules/immediate/lib/index.js:61:18)
    at process._tickCallback (node.js:924:13)''
```

But our pipe (`incomingStream.pipe(incoming).pipe(incomingStream);`) is still alive and we are trying to write data from `incomingStream` into dead `incoming`.

**Comment by andrew-aladev** [comment]
We are receiving a segfault with spider monkey on desktop with 100% chance.

**Comment by yaronyg** [comment]
@andrew-aladev I noticed that you are outputting content from data events. I wonder if you are running into thaliproject/jxcore#71? If you don't touch the buffers you get on the streams do you still get the segfault?

**Comment by chapko** [comment]
@yaronyg I have just added simple recreate logic for ECONNRESET and ECONNREFUSED errors and on desktop everything seems fine but on devices I'm getting errors:

```
11-03 21:09:43.353 14928 14975 I jxcore-log: 2016-11-03 18:09:43 - WARN createPeerListener: 'callNative for BC:75:74:3A:BC:B7-19 failed with Connection to peer [<no peer name> BC:75:74:3A:BC:B7 18] failed: Failed to connect (tried 1 time(s)): read failed, socket might closed or timeout, read ret: -1'
```

You can find it in the 1.log below.

- [1.log](https://gist.github.com/chapko/4dc96c5c7348240231b936e1ebda1b91/raw/73d9a08759077ba805c16b7a9f4e4f7d19490fb9/1.log)
- [2.log](https://gist.github.com/chapko/4dc96c5c7348240231b936e1ebda1b91/raw/73d9a08759077ba805c16b7a9f4e4f7d19490fb9/2.log)

I put my changes into `master_yarong_1446-retries-fix` branch

**Comment by chapko** [comment]
I've added some fixes. Here are logs (ran on 06bee8b commit)
- [1.log](https://gist.github.com/chapko/392c4863149e17a9df85479ad8c8b126/raw/5985595d0013bc11c622784d221fffa598c7ebac/1.log)
- [2.log](https://gist.github.com/chapko/392c4863149e17a9df85479ad8c8b126/raw/5985595d0013bc11c622784d221fffa598c7ebac/2.log)

I'm going to investigate it tommorrow

**Comment by yaronyg** [comment]
Both of the final logs return with no activity time outs. That is correct. So what is the problem with the last logs you gave above?

**Comment by chapko** [comment]
I was running "test 1" from the thali test app (Andrew's branch). This test, I believe, should run infinitely, by it failed because of the test timeout (not "no activity" timeout) and exited with code 3. I'm not sure if this is a thali bug or a test bug.

**Comment by andrew-aladev** [comment]
This can be possible connected with [this issue](http://stackoverflow.com/questions/28853815/nodejs-crash-with-multiple-request/40485779#40485779).

**Comment by andrew-aladev** [comment]
I've collected all required information about this issue.

0. We have a duplex pipe (for example `incoming.pipe(incomingStream).pipe(incoming)`).
1. We are destroying socket from `pipe` (for example `incoming`).
2. We are calling `incoming.destroy`.
3. `incoming` emits `finish` event.
4. We are waiting for `finish` event.
5. `lib/net` is waiting for `finish` event [here](https://github.com/thaliproject/jxcore/blob/master/lib/net.js#L144).
6. We are calling `incomingStream.destroy` in our `finish` handler. But this doesn't matter.
7. `function onSocketFinish` from `lib/net` is called [here](https://github.com/thaliproject/jxcore/blob/master/lib/net.js#L170).
8. `onSocketFinish` creates a shutdown request.
9. Our stream will be destroyed after this shutdown request, so we will have a not null `stream->shutdown_req` in `uv__stream_destroy` [here](https://github.com/libuv/libuv/blob/v0.10/src/unix/stream.c#L488).
10. We will receive `process._errno === ECANCELED` in `function onread` [here](https://github.com/thaliproject/jxcore/blob/master/lib/net.js#L453).
11. `_destroy` will be called with `process._errno` as first argument [here](https://github.com/thaliproject/jxcore/blob/master/lib/net.js#L390).
12. `fireErrorCallbacks` will be called anyway. It wont respect `destroyed = true`. So order of `destroy` calls doesn't matter.
13. So we should see `ECONNREFUSED` always.

But we couldn't see `ECONNREFUSED` with wifi. Why? `close` from `lib/net` will be unbind `onread` from our socket and we will just ignore `process._errno` in this case.

Result
1. If `close` is faster than `onread` we will just ignore `process._errno` and we won't see `ECONNREFUSED`
2. If `onread` is faster than `close` we will see `ECONNREFUSED`.

**Comment by andrew-aladev** [comment]
We've found [another problem](https://github.com/nodejs/node/issues/9533) that produces a 500 error for us.

**Comment by andrew-aladev** [comment]
`Socket hang up` is [meaningless](https://github.com/thaliproject/jxcore/blob/master/lib/http.js#L1146).

```
function socketCloseListener() {
  ...
  } else if (!req.res && !req._hadError) {
    var error = createHangUpError(1);
```

It will create `hang up` without any error if it couldn't obtain a response. Why? Because [`request` need it](https://github.com/request/request/blob/master/request.js#L829).

```
  if (self.req && self.req._reusedSocket && error.code === 'ECONNRESET'
      && self.agent.addRequestNoreuse) {
    self.agent = { addRequest: self.agent.addRequestNoreuse.bind(self.agent) }
    self.start()
    self.req.end()
    return
  }
```

So we have an infinite loop. We couldn't cancel our replication. Why? `pouchdb` will try to `abort` current `request`. `request` will try to `destroy` `lib/tls` socket. It will throw a `socket hang up` and this will be a reason for request to recreate itself.

**Comment by yaronyg** [comment]
I suspect that when we are the ones who are responsible for closing things down then we need a flag somewhere on the replication action that tells us that so that when the replication exits with a 500 we can check the flag and realize that it's a meaningless failure and in fact we exited as expected. This flag should probably be hooked to both kill as well as to replication time out.

**Comment by andrew-aladev** [comment]
I've found a reliable way to reproduce and understand this issue.

1. notification or replication action creates a request.
2. request creates https request.
3, https request creates a tls socket.
4. tls socket creates a raw underlying socket with forever agent.
5. this socket connects to the server.
6. server creates a new raw `incoming` socket.
7. we have a pair: request socket <-> `incoming`.
8. openssl is doing a handshake through `incoming` socket.
9. tls socket is waiting for `secureConnection` event.

Than we can see the issue:

1. sometimes openssl is not able to do a handshake, it is not able to send and receive all required data.
2. tls socket is not able to emit `secureConnection` event.
3. we are destroying `incoming` socket and server.
4. `lib/net` will try to send a [shutdown request](https://github.com/thaliproject/jxcore/blob/master/lib/net.js#L188) to destroy a request socket.
5. `lib/http` see that underlying request socket was closed and we have no error.
6. `!req.res && !req._hadError` is true and `lib/http` provides a `hang up`.
7. request receives `hang up` and [recreates itself](https://github.com/request/request/blob/master/request.js#L834).
8. request is going to create another raw socket and connect to the destroyed server.
9. this connection attempt returns `ECONNREFUSED`.

**Comment by andrew-aladev** [comment]
I've finished today with debugging this issue.

In [`deps/uv/src/unix/kqueue.c`](https://github.com/thaliproject/jxcore/blob/master/deps/uv/src/unix/kqueue.c) we have [`void uv__io_poll_jx`](https://github.com/thaliproject/jxcore/blob/master/deps/uv/src/unix/kqueue.c#L49).

I've checked that our `uv__read` call was cased by [`w->cb(loop, w, revents);`](https://github.com/thaliproject/jxcore/blob/master/deps/uv/src/unix/kqueue.c#L241).

We can add here:

```
fprintf(
  stderr,
  "ololo new event from kqueue, vnode: %d, read: %d, write: %d, flags: %d, fflags: %d\n",
  ev->filter == EVFILT_VNODE, ev->filter == EVFILT_READ, ev->filter == EVFILT_WRITE, ev->flags, ev->fflags
);
```

This will produce:
```
new event from kqueue, vnode: 0, read: 1, write: 0, flags: 32769, fflags: 0
new event, in: 1, err: 0, hup: 0
uv__read, stream: 0x100d472e8
system read, nread: 0, errno: 35, stream: 0x100d472e8
onread, stream: 0x100d472e8, nread: -1, errno: 1
socket onread received EOF, id: 9
```

`flags: 32769` means `flags = EV_ADD | EV_EOF`. So we received 0 bytes when `POLLIN` is active and we received special kqueue flag `EV_EOF`.

So our [peer connection](https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/test/www/jxcore/lib/wifiBasedNativeMock.js#L593) was closed, because the remote peer closed connection.

**Comment by yaronyg** [comment]
But why did the remote peer close the connection?

Scenario:
Time 0 - Device A opens a Bluetooth connection to Device B
Time 1 - Device A starts replicating with Device B
Time 2 - Device A fails replication with a 500 because Device B closed the connection

Why did Device B close the connection?

There is literally no logic anywhere in Express-PouchDB that would close a connection on the server side. It only closes in response to the client closing a connection.

So either the Bluetooth connection was lost (in which case you should see a nonTCPPeerAvailabilityChanged event in the logs with a null port not to mention error messages from the Android layer) or we have a bug in Express that is closing connections for some bizarre reason.

**Comment by andrew-aladev** [comment]
Today we've found that jxcore special timers don't want to work with our timeout:

```
NON_TCP_PEER_UNAVAILABILITY_THRESHOLD: 1000 * 60 * 60 * 24 * 365 * 10
```

```
var time = new Date();
logger.debug('set socket timeout: %d', thaliConfig.NON_TCP_PEER_UNAVAILABILITY_THRESHOLD);
incoming.setTimeout(thaliConfig.NON_TCP_PEER_UNAVAILABILITY_THRESHOLD, function () {
  logger.debug('socket timeout, time: %d', new Date() - time);
});
```

We will receive:
```
set socket timeout: 315360000000
socket timeout, time: 5001
```

This 5000 goes from `lib/jx/_jx_timers.js`. We can see that `this.enroll = function(item, tsecs) {` was called with `tsecs: 63072000`. 63072000 I less than `(1 << 31) -1`. So this will be an issue for jxcore. 9 years timeout works fine, 10 years timeout is broken.

We can workaround this issue by using 10 days timeout instead of 10 years. This number `1000 * 60 * 60 * 10` is less than `(1 << 31) - 1`. It will keep everyone happy.

**Comment by andrew-aladev** [comment]
I am going to provide a workaround for [jxcore issue](https://github.com/thaliproject/jxcore/issues/75).
