### ISSUE TITLE
Sometimes we got FileNotFoundException before jxcore initialized

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1425]
Please look at 
https://gist.githubusercontent.com/evabishchevich/9f1e0e0a5e826d0f94e13688b3d2bdca/raw/e5bf0da38278e5bfaf7cb6ada9ab24a2d34dd15a/gistfile1.txt

line 
20:38:05.915 18926-19010/com.example.ThaliTestApp W/System.err: java.io.FileNotFoundException:

Sometimes we saw similar error in out ThaliTest. The package can be different

**Comment by enricogior** [comment]
What about the previous lines:
```
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp E/filemap: mmap(1761280,0) failed: Invalid argument
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/asset: create map from entry failed
```
is that the expected behavior?

**Comment by yaronyg** [comment]
I'm fairly sure those lines came from JXcore, not any of our logic. If you look down the log you will see that the JXcore engine hasn't even started yet.

**Comment by enricogior** [comment]
I've searched for a reference to mmap in jxcore code, I've found entries only in V8 and SM code, but at that point of the app startup, the javascript engine hasn't been started yet, so I would call them out.

**Comment by enricogior** [comment]
To recap, the problem occurred using ThaliTestApp https://github.com/thaliproject/ThaliTestApp

The error log is:
```
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp E/filemap: mmap(1761280,0) failed: Invalid argument
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/asset: create map from entry failed
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/jxcore-FileManager: aproxFileSize failed
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/System.err: java.io.FileNotFoundException: www/jxcore/node_modules/thali/install/node_modules/findit/test/stop/q/y
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:363)
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/System.err:     at io.jxcore.node.FileManager.aproxFileSize(FileManager.java:48)
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/System.err:     at io.jxcore.node.jxcore.Initialize(jxcore.java:281)
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/System.err:     at io.jxcore.node.jxcore.access$200(jxcore.java:25)
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/System.err:     at io.jxcore.node.jxcore$6.run(jxcore.java:343)
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/System.err:     at android.os.Looper.loop(Looper.java:158)
10-25 20:38:05.915 18926-19010/com.example.ThaliTestApp W/System.err:     at io.jxcore.node.CoreThread.run(CoreRunnable.java:56)
10-25 20:38:06.025 18926-19010/com.example.ThaliTestApp W/jxcore-log: Initializing JXcore engine
10-25 20:38:06.025 18926-19010/com.example.ThaliTestApp W/jxcore-log: JXcore engine is ready
```
