### ISSUE TITLE
Tests don't start on iOS devices

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1732]
@enricogior said that he couldn't start tests on iOS device from current iOS branch even removed 
```
if (platform.isIOS) {
  // Disable node tests for iOS due to issue #1343
  console.log('****TEST_LOGGER:[PROCESS_ON_EXIT_SUCCESS]****');
  return;
}
```

**Comment by dersim-davaod** [comment]
I'm almost 100% sure that the reason of issue is one of following:
1. You're trying to edit a wrong file. Right file is located in `ThaliTest/platforms/ios/www/jxcore/app.js`
2. You should change `minDevices` number for iOS platform. File that contains this setting is located in `Thali_CordovaPlugin/test/TestServer/config/UnitTest.js`. Default values are:
```
    ios: 3,
    android: 3,
    desktop: 3
```
but if you're running only iOS platform you can use following:

```
    ios: 2,
    android: 0,
    desktop: 0
```

Then build plugin one more time.

**Comment by enricogior** [comment]
@dersim-davaod the tests start but they fail:
```
2017-01-17 16:57:11 - ERROR UnitTestFramework: '#run failed: 'Can shift large amounts of data', error: 'TimeoutError: timeout exceeded, event: 'run_Can shift large amounts of data_finished', test: 'Can shift large amounts of data'', stack: 'TimeoutError: timeout exceeded, event: 'run_Can shift large amounts of data_finished', test: 'Can shift large amounts of data'
    at afterTimeout (/Users/enrico/temp2/Thali_CordovaPlugin/test/TestServer/node_modules/bluebird/js/release/timers.js:49:15)
    at timeoutTimeout [as _onTimeout] (/Users/enrico/temp2/Thali_CordovaPlugin/test/TestServer/node_modules/bluebird/js/release/timers.js:76:13)
    at Timer.listOnTimeout [as ontimeout] (timers.js:120:15)''
2017-01-17 16:57:11 - ERROR UnitTestFramework: 'failed to run unit tests, platformName: 'ios', error: 'TimeoutError: timeout exceeded, event: 'run_Can shift large amounts of data_finished', test: 'Can shift large amounts of data'', stack: 'TimeoutError: timeout exceeded, event: 'run_Can shift large amounts of data_finished', test: 'Can shift large amounts of data'
    at afterTimeout (/Users/enrico/temp2/Thali_CordovaPlugin/test/TestServer/node_modules/bluebird/js/release/timers.js:49:15)
    at timeoutTimeout [as _onTimeout] (/Users/enrico/temp2/Thali_CordovaPlugin/test/TestServer/node_modules/bluebird/js/release/timers.js:76:13)
```

Is that a known issue? Do you need the full log from the devices?

**Comment by evabishchevich** [comment]
@dersim-davaod @enricogior  You don't need to rebuild the whole plugin, just change settings to 
```
 ios: 2,
 android: 3,
 desktop: 3
```
and restart test server

**Comment by dersim-davaod** [comment]
@evabishchevich, thanks for pointing that.
@enricogior, yes we know this issue, I'll manage it today, thanks.
