### ISSUE TITLE
Bluetooth unexpectedly turns off on the Samsung S7 devices

### ISSUE THREAD

**Issue by chapko** [thaliproject/Thali_CordovaPlugin#1738]
See the [thali03_samsung-SM-G930F.md](https://raw.githubusercontent.com/ThaliTester/TestResults/1019105739e32531_Fix_failing_test___1725_and__1731__chapko/thali03_samsung-SM-G930F.md) from [CI logs](https://github.com/ThaliTester/TestResults/tree/1019105739e32531_Fix_failing_test___1725_and__1731__chapko/) from the #1735 PR:

```
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: android.os.DeadObjectException
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at android.os.BinderProxy.transactNative(Native Method)
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at android.os.BinderProxy.transact(Binder.java:503)
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at android.bluetooth.IBluetooth$Stub$Proxy.getState(IBluetooth.java:1290)
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at android.bluetooth.BluetoothAdapter.getState(BluetoothAdapter.java:1086)
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at com.broadcom.bt.service.bleaudio.BluetoothLeAudio$1.onServiceDisconnected(BluetoothLeAudio.java:215)
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1340)
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1354)
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at android.os.Handler.handleCallback(Handler.java:739)
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at android.os.Looper.loop(Looper.java:158)
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at android.app.ActivityThread.main(ActivityThread.java:7229)
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at java.lang.reflect.Method.invoke(Native Method)
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
01-18 14:06:04.101  3948  3948 E BluetoothAdapter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

...

01-18 14:06:05.271  9723  9788 I jxcore-log: not ok 106 Can call startUpdateAdvertisingAndListening without error
01-18 14:06:05.271  9723  9788 I jxcore-log: 
01-18 14:06:05.271  9723  9788 I jxcore-log:   ---
01-18 14:06:05.271  9723  9788 I jxcore-log: 
01-18 14:06:05.271  9723  9788 I jxcore-log:     operator: notOk
01-18 14:06:05.271  9723  9788 I jxcore-log: 
01-18 14:06:05.271  9723  9788 I jxcore-log:     expected:
01-18 14:06:05.271  9723  9788 I jxcore-log: 
01-18 14:06:05.271  9723  9788 I jxcore-log:       false
01-18 14:06:05.271  9723  9788 I jxcore-log: 
01-18 14:06:05.271  9723  9788 I jxcore-log:     actual:
01-18 14:06:05.271  9723  9788 I jxcore-log: 
01-18 14:06:05.271  9723  9788 I jxcore-log:       'Failed to start the connection manager (Bluetooth connection listener)'
01-18 14:06:05.271  9723  9788 I jxcore-log: 
01-18 14:06:05.271  9723  9788 I jxcore-log:   ...
01-18 14:06:05.271  9723  9788 I jxcore-log: 

...

01-18 14:06:05.291  9723  9788 I jxcore-log: not ok 107 Can call startListeningForAdvertisements without error
01-18 14:06:05.291  9723  9788 I jxcore-log: 
01-18 14:06:05.291  9723  9788 I jxcore-log:   ---
01-18 14:06:05.291  9723  9788 I jxcore-log: 
01-18 14:06:05.291  9723  9788 I jxcore-log:     operator: notOk
01-18 14:06:05.291  9723  9788 I jxcore-log: 
01-18 14:06:05.291  9723  9788 I jxcore-log:     expected: false
01-18 14:06:05.291  9723  9788 I jxcore-log: 
01-18 14:06:05.291  9723  9788 I jxcore-log:     actual:   'Radio Turned Off'
01-18 14:06:05.291  9723  9788 I jxcore-log: 
01-18 14:06:05.291  9723  9788 I jxcore-log:   ...
01-18 14:06:05.291  9723  9788 I jxcore-log:
```

**Comment by evabishchevich** [comment]
The same situation is here
https://github.com/ThaliTester/TestResults/tree/102585911579949a_Add_null_sending_in_JSON_between_Android_and_Node_evabishchevich/

**Comment by chapko** [comment]
More logs: https://github.com/chapko/thali-logs/tree/can-shift-deadobject/2017-02-17T13:16:33.687Z

The most relevant logs are from the device [ad081603480f209327](https://raw.githubusercontent.com/chapko/thali-logs/can-shift-deadobject/2017-02-17T13%3A16%3A33.687Z/SM_G930F%20(ad081603480f209327).log):

```
02-17 16:17:26.260 18328 18531 I jxcore-log: # Can shift large amounts of data
...
02-17 16:17:28.150 18328 18531 I io.jxcore.node.ConnectionHelper: connect: Trying to connect to peer with ID 34:8A:7B:75:6B:43
...
02-17 16:17:32.150  3663  3700 W BroadcastQueue: android.os.DeadObjectException
...
02-17 16:17:33.820 18328 18531 I jxcore-log: 2017-02-17 13:17:33 - DEBUG thaliMobileNativeWrapper: 'networkChanged: {"bluetoothLowEnergy":"off","bluetooth":"off","wifi":"on","cellular":"doNotCare","bssidName":"70:cd:60:ff:5a:07","ssidName":"U"}'
...
02-17 16:17:33.880 18328 18531 I jxcore-log: 2017-02-17 13:17:33 - INFO testThaliMobileNative: 'Connection info: {"listeningPort":58147,"clientPort":0,"serverPort":0}'
...
02-17 16:17:33.890 18328 18531 I jxcore-log: 2017-02-17 13:17:33 - INFO testThaliMobileNative: 'Connected to the 58147'
...
02-17 16:17:34.240 18328 18531 I jxcore-log: 2017-02-17 13:17:34 - DEBUG thaliMobileNativeWrapper: 'networkChanged: {"bluetoothLowEnergy":"on","bluetooth":"on","wifi":"on","cellular":"doNotCare","bssidName":"70:cd:60:ff:5a:07","ssidName":"U"}'
```
These lines clearly shows that Bluetooth failed with exception but we got success result in `Mobile('connect')` callback with native listening port and were able to successfully connect to this port from node. But probably native listener was in the inconsistent state and test just failed.

Such system errors are probably inevitable but is there any way to detect these failures and destroy existing connections between node and native layer? In this case we can at least handle this failure and try to reconnect again.
