### ISSUE TITLE
Desktop test sometimes fails with error: `addMembership ENOMEM`

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#587]
For some reason, the desktop test run may fail like:

```
# #startUpdateAdvertisingAndListening should start hosting given router object
Uncaught Exception: Error: addMembership ENOMEM
Error: addMembership ENOMEM
    at new errnoException (dgram.js:387:11)
    at Socket.addMembership (dgram.js:339:11)
    at addMembership (/Users/vjrantal/Software/Thali/node-ssdp/lib/index.js:190:19)
    at Socket.onSocketListening (/Users/vjrantal/Software/Thali/node-ssdp/lib/index.js:186:5)
    at Socket.emit (events.js:98:20)
    at startListening (dgram.js:109:10)
    at dgram.js:181:7
    at dns.js:49:18
    at process._tickCallback (node.js:917:13)
```

The root cause is unknown, but almost like the failure happens on the first run after full reboot of the host machine.

The fix should be done in the used `node-ssdp` library by catching and handling properly the ENOMEM error.

**Comment by vjrantal** [comment]
Fixed.
