### ISSUE TITLE
App fails to load on some devices to error "No such native module"

### ISSUE THREAD

**Issue by vjrantal** [thaliproject/Thali_CordovaPlugin#594]
From the latest CI results, we can see that there was this many devices:
```
$ grep "BLE is" *
thali01_LGE-LG-H815.md:I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 8549): setDiscoveryMode: Discovery mode BLE is supported
thali02_LGE-LG-D722.md:I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 4569): setDiscoveryMode: Discovery mode BLE is supported
thali02_LGE-Nexus 5.md:,I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 2892): setDiscoveryMode: Discovery mode BLE is supported
thali03_LGE-LG-D855.md:I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 6047): setDiscoveryMode: Discovery mode BLE is supported
thali04_motorola-XT1072.md:,I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 5134): setDiscoveryMode: Discovery mode BLE is supported
thali04_samsung-SM-G900F.md:I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 6955): setDiscoveryMode: Discovery mode BLE is supported
thali04_samsung-SM-N910C.md:I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings(11025): setDiscoveryMode: Discovery mode BLE is supported
thali05_htc-Nexus 9.md:,I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 2201): setDiscoveryMode: Discovery mode BLE is supported
thali05_motorola-Nexus 6.md:,I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 3165): setDiscoveryMode: Discovery mode BLE is supported
thali05_samsung-SM-N9005.md:I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 6521): setDiscoveryMode: Discovery mode BLE is supported
thali06_HTC-HTC One M8s.md:,I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 5815): setDiscoveryMode: Discovery mode BLE is supported
thali06_samsung-SM-A300FU.md:I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 5365): setDiscoveryMode: Discovery mode BLE is supported
thali07_samsung-SM-A500FU.md:I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 5371): setDiscoveryMode: Discovery mode BLE is supported
thali07_samsung-SM-G900F.md:I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 6201): setDiscoveryMode: Discovery mode BLE is supported
thali08_samsung-SM-A300FU.md:,I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings( 4966): setDiscoveryMode: Discovery mode BLE is supported
```
But none of them print `BLE multiple advertisement not supported` which should happen if a truthy value is returned from the call:
```
$ grep "BLE multiple" *
thali01_LGE-LG-H815.md:,I/jxcore-log( 8549): BLE multiple advertisement supported
thali02_LGE-LG-D722.md:I/jxcore-log( 4569): BLE multiple advertisement supported
thali02_LGE-Nexus 5.md:I/jxcore-log( 2892): BLE multiple advertisement supported
thali03_LGE-LG-D855.md:I/jxcore-log( 6047): BLE multiple advertisement supported
thali04_samsung-SM-G900F.md:,I/jxcore-log( 6955): BLE multiple advertisement supported
thali04_samsung-SM-N910C.md:,I/jxcore-log(11025): BLE multiple advertisement supported
thali05_motorola-Nexus 6.md:,I/jxcore-log( 3165): BLE multiple advertisement supported
thali05_samsung-SM-N9005.md:I/jxcore-log( 6521): BLE multiple advertisement supported
thali07_samsung-SM-G900F.md:,I/jxcore-log( 6201): BLE multiple advertisement supported
```

**Comment by vjrantal** [comment]
@tompaana: Here is an example log where no return is received https://github.com/ThaliTester/TestResults/blob/61362366121daa0_Make_CI_build_and_unit_tests_pass_vjrantal/thali06_samsung-SM-A300FU.md but as I mentioned you offline, it looks like this is because the app fails to load and is exited. I don't know yet why the app fails to load, i.e., is it because of too low API level or something missing from the Bluetooth stack.

**Comment by vjrantal** [comment]
```$ grep "App.js file failed to load" *
thali01_samsung-SM-A500FU.md:,I/chromium( 5403): [INFO:CONSOLE(54)] "App.js file failed to load : "No such native module /data/data/com.test.thalitest/files/www/jxcore/app.js\nError: No such native module /data/data/com.test.thalitest/files/www/jxcore/app.js\n    at $h.require@node.js:1472:1\n    at internal_methods.loadMainFile@main.js.js:260:5\n    at JXMobile.executeJSON@main.js.js:279:7\n    at @JX_Evaluate:1:1\n"", source: file:///android_asset/www/js/thali_main.js (54)
thali04_motorola-XT1072.md:,I/chromium( 5297): [INFO:CONSOLE(54)] "App.js file failed to load : "No such native module /data/data/com.test.thalitest/files/www/jxcore/app.js\nError: No such native module /data/data/com.test.thalitest/files/www/jxcore/app.js\n    at $h.require@node.js:1472:1\n    at internal_methods.loadMainFile@main.js.js:260:5\n    at JXMobile.executeJSON@main.js.js:279:7\n    at @JX_Evaluate:1:1\n"", source: file:///android_asset/www/js/thali_main.js (54)
thali05_htc-Nexus 9.md:,I/chromium( 2214): [INFO:CONSOLE(54)] "App.js file failed to load : "No such native module /data/data/com.test.thalitest/files/www/jxcore/app.js\nError: No such native module /data/data/com.test.thalitest/files/www/jxcore/app.js\n    at $h.require@node.js:1472:1\n    at internal_methods.loadMainFile@main.js.js:260:5\n    at JXMobile.executeJSON@main.js.js:279:7\n    at @JX_Evaluate:1:1\n"", source: file:///android_asset/www/js/thali_main.js (54)
thali06_HTC-HTC One M8s.md:,I/chromium( 5956): [INFO:CONSOLE(54)] "App.js file failed to load : "No such native module /data/data/com.test.thalitest/files/www/jxcore/app.js\nError: No such native module /data/data/com.test.thalitest/files/www/jxcore/app.js\n    at $h.require@node.js:1472:1\n    at internal_methods.loadMainFile@main.js.js:260:5\n    at JXMobile.executeJSON@main.js.js:279:7\n    at @JX_Evaluate:1:1\n"", source: file:///android_asset/www/js/thali_main.js (54)
thali06_samsung-SM-A300FU.md:,I/chromium( 5272): [INFO:CONSOLE(54)] "App.js file failed to load : "No such native module /data/data/com.test.thalitest/files/www/jxcore/app.js\nError: No such native module /data/data/com.test.thalitest/files/www/jxcore/app.js\n    at $h.require@node.js:1472:1\n    at internal_methods.loadMainFile@main.js.js:260:5\n    at JXMobile.executeJSON@main.js.js:279:7\n    at @JX_Evaluate:1:1\n"", source: file:///android_asset/www/js/thali_main.js (54)
thali07_samsung-SM-A500FU.md:,I/chromium( 5443): [INFO:CONSOLE(54)] "App.js file failed to load : "No such native module /data/data/com.test.thalitest/files/www/jxcore/app.js\nError: No such native module /data/data/com.test.thalitest/files/www/jxcore/app.js\n    at $h.require@node.js:1472:1\n    at internal_methods.loadMainFile@main.js.js:260:5\n    at JXMobile.executeJSON@main.js.js:279:7\n    at @JX_Evaluate:1:1\n"", source: file:///android_asset/www/js/thali_main.js (54)
```

**Comment by vjrantal** [comment]
@yaronyg, @tompaana: above list of devices on which we see this issue.

**Comment by yaronyg** [comment]
I believe I have a Nexus 9 but I'm seriously slammed right now. @tompaana if you can't find any other way to repro this (e.g. if you don't have any of these devices) then let me know and I'll try to repro myself.

**Comment by vjrantal** [comment]
This can be reproduced with TestDummy by updating it to latest jxcore-cordova. Example results via here https://github.com/thaliproject/TestDummy/pull/51#issuecomment-192259912.

**Comment by yaronyg** [comment]
@obastemur There seems to be a bug in JXcore, we have a repo above. Can you look at it?

**Comment by obastemur** [comment]
I don't think this is a jxcore issue. sent a message to @vjrantal separately.

**Comment by vjrantal** [comment]
This has something to do with building the app with `cordova build android --release --device` and signing it. We were not able to reproduce locally where we use debug builds, but myself @czyzm were able to reproduce outside of CI when signed production builds were used.

This doesn't happen on all devices.

This seems to also have something to do with latest jxcore-cordova, because this issue was never triggered with releases older than 0.1.0. Not that the issue is necessarily there, but somehow only latest releases trigger this problem.

I tried if running zipalign for the signed apk helps, but that did not help and the issue persists after zipalign.

**Comment by cicorias** [comment]
Could it be outdated root certificates on the device? We are using NDK 4.9 now, not 4.8.

**Comment by vjrantal** [comment]
I don't think it is that since the app installs fine, i.e., the OS does not reject the installation due to certificate issues. I would have wanted to check the app folder after installation in case there ends up being some delta between working and non-working phones, but I'd need root for that. Alternative would be to install to phone that support installation to SD card and check the SD card content after installation.

**Comment by blissland** [comment]
FYI I think I found a fix for this issue:

https://github.com/jxcore/jxcore-cordova/issues/144

**Comment by yaronyg** [comment]
@blissland This is awesome! We'll have to set up testing for this.

**Comment by yaronyg** [comment]
@enricogior As you can see in the link published by blissland the fix to this problem is really easy and this issue is hurting our ability to run tests in CI so can we please combine this with the fix to #763?

**Comment by enricogior** [comment]
I cherry-picked @blissland fix:
https://github.com/thaliproject/jxcore/commit/9f9ab7b4d563ec22c64c4b976d41b43110565380
I'll send the PR after checking with @yaronyg.

**Comment by enricogior** [comment]
PR submitted https://github.com/thaliproject/jxcore/pull/11
