### ISSUE TITLE
Test does not wait for Bluetooth to be re-enabled

### ISSUE THREAD

**Issue by tompaana** [thaliproject/Thali_CordovaPlugin#717]
Test in `testThaliMobileNativeWrapper.js` Bluetooth connection is toggled, but when it's turned back on, it is not awaited resulting in a fatal error:

```
04-25 02:25:14.116 15336-15480/com.test.thalitest I/jxcore-log: # 70. can do HTTP requests after connections are cut
04-25 02:25:14.118 15336-15480/com.test.thalitest I/jxcore-log: DEBUG thaliMobileNativeWrapper: networkChanged: {"bluetoothLowEnergy":"off","bluetooth":"off","wifi":"on","cellular":"doNotCare","bssidName":"ce:5d:4e:a0:68:4c"}
04-25 02:25:14.120 15336-15336/com.test.thalitest V/io.jxcore.node.ConnectivityMonitor: updateConnectivityInfo: No relevant state changes
04-25 02:25:14.120 15336-15336/com.test.thalitest I/org.thaliproject.p2p.btconnectorlib.DiscoveryManager: onBluetoothAdapterScanModeChanged: Mode changed to 20
04-25 02:25:14.163 15336-15480/com.test.thalitest I/jxcore-log: DEBUG createNativeListener: creating native server
04-25 02:25:14.164 15336-15480/com.test.thalitest I/jxcore-log: DEBUG createNativeListener: listening 43459
04-25 02:25:14.166 15336-15480/com.test.thalitest I/io.jxcore.node.ConnectionHelper: start: Port number: 45623, start advertisements: false
04-25 02:25:14.166 15336-15480/com.test.thalitest I/io.jxcore.node.ConnectionHelper: restoreDefaultBleDiscoverySettings: Powering the BLE discovery back up
04-25 02:25:14.166 15336-15480/com.test.thalitest I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings: setAdvertiseMode: 0 -> 2
04-25 02:25:14.167 15336-15480/com.test.thalitest I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings: setAdvertiseTxPowerLevel: 1 -> 3
04-25 02:25:14.167 15336-15480/com.test.thalitest I/org.thaliproject.p2p.btconnectorlib.DiscoveryManagerSettings: setScanMode: 0 -> 2
04-25 02:25:14.167 15336-15480/com.test.thalitest V/io.jxcore.node.ConnectivityMonitor: start: Already started
04-25 02:25:14.167 15336-15480/com.test.thalitest V/io.jxcore.node.StartStopOperation: isTargetState: Connectivity: NOT_STARTED, discovery: WAITING_FOR_SERVICES_TO_BE_ENABLED, is discovering: false, is advertising: false - Start operation: Should affect listening to advertisements only
04-25 02:25:14.167 15336-15480/com.test.thalitest V/io.jxcore.node.StartStopOperationHandler: executeCurrentOperation: Executing: Start operation: Should affect listening to advertisements only
04-25 02:25:14.167 15336-15480/com.test.thalitest I/org.thaliproject.p2p.btconnectorlib.DiscoveryManager: start: Discovery mode: BLE, start discovery: true, start advertiser: false
04-25 02:25:14.168 15336-15480/com.test.thalitest E/org.thaliproject.p2p.btconnectorlib.DiscoveryManager: start: Cannot start BLE based peer discovery, because Bluetooth is not enabled on the device
04-25 02:25:14.168 15336-15480/com.test.thalitest D/org.thaliproject.p2p.btconnectorlib.DiscoveryManager: updateState: State: NOT_STARTED, is discovering: false, is advertising: false
04-25 02:25:14.168 15336-15480/com.test.thalitest E/io.jxcore.node.StartStopOperationHandler: executeCurrentOperation: Failed to start the discovery manager
04-25 02:25:14.168 15336-15480/com.test.thalitest I/io.jxcore.node.ConnectionHelper: start: OK
04-25 02:25:14.169 15336-15336/com.test.thalitest I/io.jxcore.node.ConnectionHelper: onDiscoveryManagerStateChanged: State: NOT_STARTED, is discovering: false, is advertising: false
04-25 02:25:14.175 15336-15480/com.test.thalitest E/jxcore-log: Trace: [Error: Failed to start the discovery manager]
                                                                    at $3.prototype.trace@console.js:139:8
                                                                    at @/data/data/com.test.thalitest/files/www/jxcore/lib/thaliTape.js:38:3
                                                                    at emit@events.js:98:1
                                                                    at handlers.reject/<@/data/data/com.test.thalitest/files/www/jxcore/node_modules/thali/node_modules/lie/lib/index.js:128:11
                                                                    at nextTick@/data/data/com.test.thalitest/files/www/jxcore/node_modules/thali/node_modules/lie/node_modules/immediate/lib/index.js:61:7
                                                                    at $0a@node.js:917:1
04-25 02:25:14.175 15336-15480/com.test.thalitest I/jxcore-log: ****TEST_LOGGER:[PROCESS_ON_EXIT_FAILED]****
```

**Comment by yaronyg** [comment]
There are two bugs here

1. We have to wait for the network changed event after toggling Bluetooth so that we know that Bluetooth is working again (this really applies more to turning bluetooth on than off)
2. Whenever we turn Bluetooth off the entire node stack seems to die, we need to figure out why and fix it, we shouldn't die when Bluetooth is off
