### ISSUE TITLE
Test JXcore on Android Nougat

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#754]
Does it work there?

**Comment by enricogior** [comment]
Preliminary results are not very good: on Nougat the test/simple tests return 65 failures compared to 15 failures on Marshmellow.

**Comment by enricogior** [comment]
```
Marshmallow Intel V8:
				[Pass  | Fail]
Internet:		[+   5 |-   1]
JXcore: 		[+ 175 |-   1]
JXcore-message: [+   3 |-   2]
Pummel:			[+  29 |-  12]
Simple: 		[+ 605 |-  17]

Nougat, Intel V8:
				[Pass  | Fail]   Fail delta compared to Marshmallow
Internet:		[+   4 |-   2]   +1
JXcore: 		[+ 173 |-   3]   +2
JXcore-message: [+   3 |-   2]   --
Pummel:			[+  28 |-  12]   +1
Simple: 		[+ 555 |-  67]   +50
```

Full results for SpiderMonkey coming soon.

**Comment by enricogior** [comment]
```
Marshmallow, x86 SM:
                [Pass  | Fail]
Internet:       [+   5 |-   1]
JXcore:         [+ 171 |-   5]
JXcore-message: [+   3 |-   2]
Pummel:         [+  32 |-   9]
Simple:         [+ 604 |-  15]

Nougat, x86 SM:
                [Pass  | Fail]   Fail delta compared to Marshmallow
Internet:       [+   4 |-   2]   +1
JXcore:         [+ 170 |-   6]   +1
JXcore-message: [+   3 |-   2]   --
Pummel:         [+  32 |-   9]   +1
Simple:         [+ 554 |-  65]   +50
```

**Comment by enricogior** [comment]
Tests in 'test/simple' that fail on Marshmallow but not on Nougat:
```
test/simple/test-child-process-double-pipe.js
test/simple/test-timer-match.js
```

Tests in 'test/simple' that fail on Nougat causing the test script to crash:
```
test/simple/test-cluster-master-kill.js
```

Tests in 'test/simple' that fail on Nougat causing the test script to hang:
```
test/simple/test-cluster-dgram-2.js
test/simple/test-cluster-eaddrinuse.js
test/simple/test-http-server-stale-close.js
```

Tests in 'test/simple' that fail on Nougat but not on Marshmallow:
```
test/simple/test-child-process-fork-and-spawn.js
test/simple/test-child-process-fork-close.js
test/simple/test-child-process-fork-dgram.js
test/simple/test-child-process-fork-exec-argv.js
test/simple/test-child-process-fork-exec-path.js
test/simple/test-child-process-fork-getconnections.js
test/simple/test-child-process-fork-net.js
test/simple/test-child-process-fork-net2.js
test/simple/test-child-process-fork.js
test/simple/test-child-process-internal.js
test/simple/test-child-process-send-utf8.js
test/simple/test-child-process-set-blocking.js
test/simple/test-child-process-stdio-inherit.js
test/simple/test-cluster-basic.js
test/simple/test-cluster-bind-twice-v1.js
test/simple/test-cluster-bind-twice-v2.js
test/simple/test-cluster-dgram-1.js
test/simple/test-cluster-disconnect.js
test/simple/test-cluster-eaccess.js
test/simple/test-cluster-fork-env.js
test/simple/test-cluster-http-pipe.js
test/simple/test-cluster-listening-port.js
test/simple/test-cluster-master-error.js
test/simple/test-cluster-message.js
test/simple/test-cluster-net-listen.js
test/simple/test-cluster-net-send.js
test/simple/test-cluster-send-deadlock.js
test/simple/test-cluster-send-handle-twice.js
test/simple/test-cluster-uncaught-exception.js
test/simple/test-cluster-worker-death.js
test/simple/test-cluster-worker-disconnect.js
test/simple/test-cluster-worker-exit.js
test/simple/test-cluster-worker-kill.js
test/simple/test-dgram-broadcast-multi-process.js
test/simple/test-domain-nested-throw.js
test/simple/test-fs-symlink.js
test/simple/test-http-client-pipe-end.js
test/simple/test-http-client-response-domain.js
test/simple/test-http-pipeline-flood.js
test/simple/test-http-unix-socket.js
test/simple/test-net-pingpong.js
test/simple/test-net-pipe-connect-errors.js
test/simple/test-pipe-address.js
test/simple/test-pipe-stream.js
test/simple/test-pipe-unref.js
test/simple/test-repl.js
test/simple/test-tls-connect-pipe.js
```

**Comment by enricogior** [comment]
Tests in 'test/simple' that fail on Nougat but not on Marshmallow, detailed info:
```
test/simple/test-child-process-env.js
Failure no 1, exit code: 8
AssertionError: false == true ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-child-process-env.js:35:1
    at emit (events.js
	
------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-exec-env.js
Failure no 2, exit code: 8
error!: 127
stdout: ""
stderr: "/system/bin/sh: /system/xbin/env: not found\n"
response:  
AssertionError: 1 == 0 ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-child-process-exec-env.js:38:3
    at emit (events.js
	
------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-fork-and-spawn.js
Failure no 3, exit code: 8
AssertionError: 8 == 0 ( 0:0)
    at equal (assert.js:136:11)
    at checkExit (/data/local/tmp/jxcore/test/simple/test-child-process-fork-and-spawn.js:29:3)
    at emit (events.js
	
------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-fork-close.js
Failure no 4, exit code: 8
AssertionError: false == true ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-child-process-fork-close.js:28:3
    at emit (events.js
	
------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-fork-dgram.js
Failure no 5, exit code: 8
Error: channel closed (child_process.js 392:19)
    at $P/$I.send (child_process.js:392:19)
    at shutdown (/data/local/tmp/jxcore/test/simple/test-child-process-fork-dgram.js:74:5)
    at sendMessages/timer</< (/data/local/tmp/jxcore/test/simple/test-child-process-fork-dgram.js:66:13)
    at $Q (dgram.js:271:1)
	
------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-fork-exec-argv.js
Failure no 6, exit code: 8
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data (/data/local/tmp/jxcore/test/simple/test-child-process-fork-exec-argv.js 28:21)
    at  (/data/local/tmp/jxcore/test/simple/test-child-process-fork-exec-argv.js:28:22)
    at emit (events.js:85:1)
    at $0h/this._handle.onexit (child_process.js:826:1)
	
------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-fork-exec-path.js
Failure no 7, exit code: 8
AssertionError: 8 == 0 ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-child-process-fork-exec-path.js:41:5
    at exports.mustCall/< (/data/local/tmp/jxcore/test/common.js:1

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-fork-getconnections.js
Failure no 8, exit code: 8
Error: child died unexpectedly! (/data/local/tmp/jxcore/test/simple/test-child-process-fork-getconnections.js 39:13)
    at  (/data/local/tmp/jxcore/test/simple/test-child-process-fork-getconnections.js:39:13)
    at emit (events.js:85:1)
    at $0h/this._handle.onexit (child_process.js:826:1)

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-fork-net.js
Failure no 9, exit code: 8
CHILD: died
AssertionError: false == true ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-child-process-fork-net.js:183:5
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-fork-net2.js
Failure no 10, exit code: 8
Error: channel closed (child_process.js 392:19)
    at $P/$I.send (child_process.js:392:19)
    at /data/local/tmp/jxcore/test/simple/test-child-process-fork-net2.js:76:9
    at emit (events.js:82:1)
    at $0f (net.js:1145:1)

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-fork.js
Failure no 11, exit code: 8
AssertionError: false == true ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-child-process-fork.js:33:3
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-internal.js
Failure no 12, exit code: 8
AssertionError: "undefined" deepEqual {"cmd":"fooNODE_"} ( 0:0)
    at deepEqual (assert.js:153:1)
    at /data/local/tmp/jxcore/test/simple/test-child-process-internal.js:37:5
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-send-utf8.js
Failure no 13, exit code: 1
Mismatched <anonymous> function calls. Expected 1, actual 0.
$w.prototype._compile@module.js:621:8
$w._extensions[".js"]@module.js:651:1
$w.prototype.load@module.js:442:1
$w._load@module.js:407:1

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-set-blocking.js
Failure no 14, exit code: 8
AssertionError: 0 == 8 ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-child-process-set-blocking.js:20:3
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-child-process-stdio-inherit.js
Failure no 15, exit code: 8
AssertionError: "" == "asdfasdf" ( 0:0)
    at equal (assert.js:136:11)
    at grandparent/< (/data/local/tmp/jxcore/test/simple/test-child-process-stdio-inherit.js:30:5)
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-basic.js
Failure no 16, exit code: 8
AssertionError: The cluster event "online" on the cluster object did not fire ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-cluster-basic.js:137:7
    at forEach/< (/data/local/tmp/jxcore/test/simple/test-cluster-basic.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-bind-twice-v1.js
Failure no 17, exit code: 8
AssertionError: false == true ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-cluster-bind-twice-v1.js:36:5
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-bind-twice-v2.js
Failure no 18, exit code: 8
Error: A exited with 8 (/data/local/tmp/jxcore/test/simple/test-cluster-bind-twice-v2.js 51:13)
    at  (/data/local/tmp/jxcore/test/simple/test-cluster-bind-twice-v2.js:51:13)
    at emit (events.js:85:1)
    at $0h/this._handle.onexit (child_process.js:826:1)

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-dgram-1.js
Failure no 19, exit code: 8
AssertionError: false == true ( 0:0)
    at ok (assert.js:126:1)
    at setupWorker/< (/data/local/tmp/jxcore/test/simple/test-cluster-dgram-1.js:70:7)
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-disconnect.js
Failure no 20, exit code: 8
AssertionError: 0 == 2 ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-cluster-disconnect.js:100:5
    at g (events.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-eaccess.js
Failure no 21, exit code: 8
master exited
AssertionError: 0 == 1 ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-cluster-eaccess.js:32:5
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-fork-env.js
Failure no 22, exit code: 8
AssertionError: The worker did not receive the correct env. ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-cluster-fork-env.js:40:5
    at g (events.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-http-pipe.js
Failure no 23, exit code: 8
AssertionError: false == true ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-cluster-http-pipe.js:25:5
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-listening-port.js
Failure no 24, exit code: 8
AssertionError: null == true ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-cluster-listening-port.js:21:5
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-master-error.js
Failure no 25, exit code: 8
AssertionError: The master did not die after an error was throwed ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-cluster-master-error.js:117:5
    at g (events.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-message.js
Failure no 26, exit code: 8
AssertionError: The master did not receive any message ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-cluster-message.js:118:7
    at forEach/< (/data/local/tmp/jxcore/test/simple/test-cluster-message.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-net-listen.js
Failure no 27, exit code: 8
AssertionError: 8 == 0 ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-cluster-net-listen.js:13:5
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-net-send.js
Failure no 28, exit code: 8
[2973] master
AssertionError: false == true ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-cluster-net-send.js:28:5
    at g (events.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-send-deadlock.js
Failure no 29, exit code: 8
AssertionError: Worker exited with an error code ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-cluster-send-deadlock.js:15:5
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-send-handle-twice.js
Failure no 30, exit code: 8
AssertionError: Worker exited with an error code ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-cluster-send-handle-twice.js:19:7
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-uncaught-exception.js
Failure no 31, exit code: 8
AssertionError: 8 == 42 ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-cluster-uncaught-exception.js:21:5
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-worker-death.js
Failure no 32, exit code: 8
AssertionError: 8 == 42 ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-cluster-worker-death.js:16:5
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-worker-disconnect.js
Failure no 33, exit code: 8
AssertionError: Suicide mode was not set ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-cluster-worker-disconnect.js:87:5
    at g (events.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-worker-exit.js
Failure no 34, exit code: 1
FAIL: the cluster exited w/ incorrect exitCode [expected: 42 / actual: 8]

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-cluster-worker-kill.js
Failure no 35, exit code: 1
FAIL: the cluster exited w/ incorrect exitCode [expected: null / actual: 8]

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-dgram-broadcast-multi-process.js
Failure no 36, exit code: 1
[PARENT] Worker 3079 died. 1 dead of 3
[PARENT] Worker 3080 died. 2 dead of 3
[PARENT] Worker 3081 died. 3 dead of 3
[PARENT] All workers have died.
[PARENT] Fail

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-domain-nested-throw.js
Failure no 37, exit code: 8
AssertionError: false == true ( 0:0)
    at ok (assert.js:126:1)
    at parent/< (/data/local/tmp/jxcore/test/simple/test-domain-nested-throw.js:28:1)
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-executable-path.js
Failure no 38, exit code: 8
debugPaths: /data/local/tmp/jxcore/out/Debug/jx,/data/local/tmp/jxcore/Debug/node
defaultPaths: /data/local/tmp/jxcore/out/Release/jx,/data/local/tmp/jxcore/Release/jx
process.execPath: /data/local/tmp/jxcore/jx
AssertionError: false == true ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-executable-path.js:34:1
    at $w.prototype._compile (module.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-fs-readfile-pipe.js
Failure no 39, exit code: 8
{ [Error: Command failed: Error: ENOENT, open '/dev/stdin' (node.js 138:7)

] killed: false, code: 8, signal: null }
AssertionError: it exits normally ( 0:0)
    at ok (assert.js:126:1)
    at /data/local/tmp/jxcore/test/simple/test-fs-readfile-pipe.js:32:1
    at $0i (child_process.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-fs-symlink.js
Failure no 40, exit code: 8
symlink done
Error: EACCES, link '/data/local/tmp/jxcore/test/fixtures/cycles/root.js' (node.js 138:7)

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-fs-watch.js
Failure no 41, exit code: 8
AssertionError: null == "watch.txt" ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-fs-watch.js:56:11
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-http-304.js
Failure no 42, exit code: 8
Server running at http://127.0.0.1:12347/
Error: Command failed: /system/bin/sh: curl: not found
 (child_process.js 665:7)
    at $0i (child_process.js:665:7)
    at emit (events.js:85:1)
    at $X (child_process.js:773:1)
    at $0h.prototype.spawn/</< (child_process.js:994:1)
    at emit (events.js:82:1)
    at $f.prototype._destroy/< (net.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-http-client-pipe-end.js
Failure no 43, exit code: 8
Error: listen EACCES (net.js 837:7)
    at $c (net.js:837:7)
    at $a.prototype._listen2 (net.js:951:9)
    at $T (net.js:997:1)
    at $a.prototype.listen (net.js:1064:1)
    at /data/local/tmp/jxcore/test/simple/test-http-client-pipe-end.js:19:1
    at $w.prototype._compile (module.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-http-client-response-domain.js
Failure no 44, exit code: 8
Error: listen EACCES (net.js 837:7)
    at $c (net.js:837:7)
    at $a.prototype._listen2 (net.js:951:9)
    at $T (net.js:997:1)
    at $a.prototype.listen (net.js:1064:1)
    at /data/local/tmp/jxcore/test/simple/test-http-client-response-domain.js:22:1
    at $w.prototype._compile (module.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-http-pipeline-flood.js
Failure no 45, exit code: 8
AssertionError: false == true ( 0:0)
    at ok (assert.js:126:1)
    at parent/</< (/data/local/tmp/jxcore/test/simple/test-http-pipeline-flood.js:49:1)
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-http-unix-socket.js
Failure no 46, exit code: 8
Error: listen EACCES (net.js 837:7)
    at $c (net.js:837:7)
    at $a.prototype._listen2 (net.js:951:9)
    at $T (net.js:997:1)
    at $a.prototype.listen (net.js:1064:1)
    at /data/local/tmp/jxcore/test/simple/test-http-unix-socket.js:23:1
    at $w.prototype._compile (module.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-net-pingpong.js
Failure no 47, exit code: 8
/data/local/tmp/jxcore/test/tmp/test.sock
Error: listen EACCES (net.js 837:7)
    at $c (net.js:837:7)
    at $a.prototype._listen2 (net.js:951:9)
    at $T (net.js:997:1)
    at $a.prototype.listen (net.js:1064:1)
    at pingPongTest (/data/local/tmp/jxcore/test/simple/test-net-pingpong.js:65:3)
    at /data/local/tmp/jxcore/test/simple/test-net-pingpong.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-net-pipe-connect-errors.js
Failure no 48, exit code: 8
Error: listen EACCES (net.js 837:7)
    at $c (net.js:837:7)
    at $a.prototype._listen2 (net.js:951:9)
    at $T (net.js:997:1)
    at $a.prototype.listen (net.js:1064:1)
    at /data/local/tmp/jxcore/test/simple/test-net-pipe-connect-errors.js:44:3
    at $w.prototype._compile (module.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-next-tick-starvation.js
Failure no 49, exit code: 8
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
Error: The timer is starving (/data/local/tmp/jxcore/test/simple/test-next-tick-starvation.js 15:1)
    at spin (/data/local/tmp/jxcore/test/simple/test-next-tick-starvation.js:15:1)
    at $0a (node.js:924:1)

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-os.js
Failure no 50, exit code: 8
AssertionError: "/data/local/tmp/jxcore/" == "/tmp" ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-os.js:22:1
    at $w.prototype._compile (module.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-pipe-address.js
Failure no 51, exit code: 8
Error: listen EACCES (net.js 837:7)
    at $c (net.js:837:7)
    at $a.prototype._listen2 (net.js:951:9)
    at $T (net.js:997:1)
    at $a.prototype.listen (net.js:1064:1)
    at /data/local/tmp/jxcore/test/simple/test-pipe-address.js:14:1
    at $w.prototype._compile (module.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-pipe-stream.js
Failure no 52, exit code: 8
Error: listen EACCES (net.js 837:7)
    at $c (net.js:837:7)
    at $a.prototype._listen2 (net.js:951:9)
    at $T (net.js:997:1)
    at $a.prototype.listen (net.js:1064:1)
    at test (/data/local/tmp/jxcore/test/simple/test-pipe-stream.js:56:3)
    at /data/local/tmp/jxcore/test/simple/test-pipe-stream.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-pipe-unref.js
Failure no 53, exit code: 8
Error: listen EACCES (net.js 837:7)
    at $c (net.js:837:7)
    at $a.prototype._listen2 (net.js:951:9)
    at $T (net.js:997:1)
    at $a.prototype.listen (net.js:1064:1)
    at /data/local/tmp/jxcore/test/simple/test-pipe-unref.js:11:1
    at $w.prototype._compile (module.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-process-config.js
Failure no 54, exit code: 8
Error: ENOENT, no such file or directory '/data/local/tmp/jxcore/config.gypi' (node.js 138:7)
    at  (native:jxcore_js_object:3:12)
    at fs.openSync (fs.js:459:8)
    at fs.readFileSync (fs.js:296:8)
    at /data/local/tmp/jxcore/test/simple/test-process-config.js:16:14
    at $w.prototype._compile (module.js:621:8)
    at $w._extensions[".js"] (module.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-process-getgroups.js
Failure no 55, exit code: 8
AssertionError: 11 == 13 ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-process-getgroups.js:19:5
    at $0i (child_process.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-repl.js
Failure no 56, exit code: 8
repl test
Error: listen EACCES (net.js 837:7)
    at $c (net.js:837:7)
    at $a.prototype._listen2 (net.js:951:9)
    at $T (net.js:997:1)
    at $a.prototype.listen (net.js:1064:1)
    at unix_test (/data/local/tmp/jxcore/test/simple/test-repl.js:336:3)
    at /data/local/tmp/jxcore/test/simple/test-repl.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-stream-pipe-multi.js
Failure no 57, exit code: 143

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-tls-connect-pipe.js
Failure no 58, exit code: 8
Error: listen EACCES (net.js 837:7)
    at $c (net.js:837:7)
    at $a.prototype._listen2 (net.js:951:9)
    at $T (net.js:997:1)
    at $a.prototype.listen (net.js:1064:1)
    at /data/local/tmp/jxcore/test/simple/test-tls-connect-pipe.js:21:1
    at $w.prototype._compile (module.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-tls-securepair-client.js
Failure no 59, exit code: 8
Error: Command failed: /system/bin/sh: openssl: not found
 (child_process.js 665:7)
    at $0i (child_process.js:665:7)
    at emit (events.js:85:1)
    at $X (child_process.js:773:1)
    at $0h.prototype.spawn/</< (child_process.js:994:1)
    at emit (events.js:82:1)
    at $f.prototype._destroy/< (net.js:

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-tls-securepair-server.js
Failure no 60, exit code: 8
AssertionError: 1 == 0 ( 0:0)
    at equal (assert.js:136:11)
    at /data/local/tmp/jxcore/test/simple/test-tls-securepair-server.js:135:3
    at emit (events.js

------------------------------------------------------------------------------------------------------------------------------------
test/simple/test-tls-set-ciphers.js
Failure no 61, exit code: 8
Error: Command failed: /system/bin/sh: openssl: not found
 (child_process.js 665:7)
    at $0i (child_process.js:665:7)
    at emit (events.js:85:1)
    at $X (child_process.js:773:1)
    at $0h.prototype.spawn/</< (child_process.js:994:1)
    at emit (events.js:82:1)
    at $f.prototype._destroy/< (net.js:

------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by yaronyg** [comment]
The first goal is to figure out why we are getting the new failures and then we can decide what we want to fix. There is at least a week of work here.

**Comment by enricogior** [comment]
Nougat ARMv8 using SM.

```
                [Pass  | Fail]
Simple:         [+ 564 |-  55]
```

Tests that hang:
```
test/simple/test-child-process-fork-net2.js
test/simple/test-cluster-dgram-2.js
```
Tests in 'test/simple' that fail on Nougat but not on Marshmallow:
```
test/simple/test-child-process-fork-exec-argv.js
test/simple/test-child-process-fork-net.js
test/simple/test-child-process-fork.js
test/simple/test-child-process-set-blocking.js
test/simple/test-child-process-stdio-inherit.js
test/simple/test-cluster-http-pipe.js
test/simple/test-fs-symlink.js
test/simple/test-http-buffer-sanity.js
test/simple/test-http-client-pipe-end.js
test/simple/test-http-client-response-domain.js
test/simple/test-http-client-timeout-event.js
test/simple/test-http-many-keep-alive-connections.js
test/simple/test-http-unix-socket.js
test/simple/test-listen-fd-detached-inherit.js
test/simple/test-listen-fd-server.js
test/simple/test-net-GH-5504.js
test/simple/test-net-pingpong.js
test/simple/test-net-pipe-connect-errors.js
test/simple/test-pipe-address.js
test/simple/test-pipe-stream.js
test/simple/test-pipe-unref.js
test/simple/test-pipe.js
test/simple/test-repl.js
test/simple/test-timers-unref.js
test/simple/test-tls-connect-pipe.js
test/simple/test-tls-fast-writing.js
test/simple/test-tls-zero-clear-in.js
```

**Comment by yaronyg** [comment]
1/2 the tests were failing because of a problem with the test runner javascript file spawning a child instance so we fixed that by using a bash script instead.

10 of the remaining 30 failing test were failing because of a pipe for locking that isn't working and we are investigating that now. So once we deal with these 10 then we have 4 or 5 tests that are failing on Nougat that aren't failing on Marshmallow.

**Comment by yaronyg** [comment]
12 tests that always failed on Marshmallow are now not failing due to work by Enrico. He thinks by today he should have 0 tests failing on Marshmallow and then will clean up Nougat. There seem to be two types of problems. In some cases the test just isn't appropriate for Android and in other cases there are small fixes needed in the tests themselves.

We will also try to rerun the tests on iOS 9 to see how the fixes apply there and we can see where we are with iOS. We now can see more clearly when a test is failing and why.

**Comment by enricogior** [comment]
Four new issues open for tests failing on Nougat:
https://github.com/thaliproject/jxcore/issues/52
https://github.com/thaliproject/jxcore/issues/53
https://github.com/thaliproject/jxcore/issues/54
https://github.com/thaliproject/jxcore/issues/55

**Comment by yaronyg** [comment]
Down to 15 bugs. 11 fail for the same reason in LibUV. The bugs have been classified above and we'll decide what to fix. The LibUV issue has to do with pipes.Another involves a symbolic link where the issue seems to be the test, not the code. In another test we fork a child and it doesn't seem to work. And the final one there is a parent and a child and the parent doesn't receive a standard output event because the child seems to exit before the event is received by the parent. So the last two are similar, we think. The last one that is still being investigated (don't have a bug for this one yet).

**Comment by enricogior** [comment]
The investigation is completed, resulting in the following issues:

https://github.com/thaliproject/jxcore/issues/52
https://github.com/thaliproject/jxcore/issues/53
https://github.com/thaliproject/jxcore/issues/54
https://github.com/thaliproject/jxcore/issues/55
https://github.com/thaliproject/jxcore/issues/56

**Comment by enricogior** [comment]
PR submitted https://github.com/thaliproject/jxcore/pull/57
